
* TODO

   - [ ] nodes/environments: vagrant/primary/worker/no_submission?
     - [ ] vagrant: motd and variables
   - [ ] .bashrc for root? (install_system.sh)
   - [ ] Distros Ubuntu (doing 20.04), RHEL (doing CentOS 8), Debian (todo)
   - [ ] ntp service (done), does it by adding it?

* Steps
  - Start vagrant (using focal/64) (to test on centos/8 with the other box) (M-m a t v V) + terminal (M-m a t v t)
    - vagrant_provision installs puppet + runs the production environment
    - Added path to root for installed gems on Vagrant
  - become sudo and get into the puppet directory ~:/etc/puppetlabs/code/environments/production#~
  - generate dependencies with ~generate-puppetfile -p ./Puppetfile~ and run the last two commands from provision (r10k install + apply)
    - ~/opt/puppetlabs/puppet/bin/r10k puppetfile install --verbose~
    - ~/opt/puppetlabs/puppet/bin/puppet apply --environment=production $(pwd)/manifests --verbose~
    - ~/opt/puppetlabs/puppet/bin/puppet lookup submitty.install~ shows the output
    - Test databases were created: ~su -c 'psql -U submitty_dbuser -d submitty' postgres~ ~\dt~ ~\d users~
    - Test puppet commands: puppet apply --noop -e '$a = ['234', 'asdf'] node default { ($a + ['poiu', '3234']).map | $item | { notice($item) } }'
  - Questions
    - can we have if blocks in hiera yaml file? (e.g., to separate vagrant/worker/etc...)

** Where are we now?
    - [X] r10k first dependencies!
    - [ ] [2021-10-17 Sun 17:33] going here: [[file:~/Documents/Work/RSDG/Projects/Teaching/submitty_stuff/Submitty/.setup/install_system.sh::bash ${SUBMITTY_INSTALL_DIR}/.setup/INSTALL_SUBMITTY.sh clean skip_web_restart][INSTALL_SUBMITTY.sh]]; 721
    - [ ] [2021-10-17 Sun 22:06] going here: [[file:~/Documents/Work/RSDG/Projects/Teaching/submitty_stuff/Submitty/.setup/INSTALL_SUBMITTY_HELPER.sh::replace necessary variables][Replace variables on copied CMakes]]; 387 -

** Problems
   - cannot ssh from vagrant!
     - change /etc/ssh/sshd_config to don't use PAM. ~UsePAM no~
   - php: ~php -r 'print PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;'~ shows that something is not right (warning xdebug as part of zend)
      - Also it shows a problem with ds, loading before json: ~/etc/php/7.4/cli/conf.d~ solved by moving json to 19.
      - 'ini-prefix' is not working? It's renamed... but not in the soft links directory.

** Submitty script map
   #+begin_src artist


     Submitty                      .setup/                                                                    /bin/                               /distro_setup/
                                /--------------------\              +--------------------------+                                                                                        {distro}/{version}/
                                |  install_system.sh +----------->  | Setup variables          |
                                |                    |              +--------------------------+
                                |                    |--------+     | !Paths / Users & groups! |           +---------------+                                                          +------------------------------+
                                |                    |        |     +--------------------------+      ---> |  versions.sh  |                                                          |  setup_distro.sh             |
                                |                    |        \--------------------------------------/     +---------------+                                                          +------------------------------+
                                |                    |              +----------------------+               | repositories  |                   +--------------------+                 |                              |
                                |                    |------------> |If Vagrant            |               |       &       |                   | setup_distro.sh    |                 |  Install basic packages      |
                                |                    |              +----------------------+               |   ext tools   |                   +--------------------+                 |                              |
                                |                    |              |Set SSH               |               +---------------+                   |                    |                 |  Install ntp                 |
                                |                    |              |Set /root/.bahsrc     |                                                   | extract distro     |                 |                              |
                                |                    |              |   - aliases          |                                                   |   version          |                 |  Install php + apache        |
                                |                    |------------- |   - services         | ----------------------------------------------->  |                    |                 |                              |
                                |                    |              |   - variables        |                                                   |                    |-------------->  |  Install programming tools   |
                                |                    |              +----------------------+                                                   |                    |                 |                              |
                                |                    |                                                                 /-----------------------|                    |                 |  Install Docker-CE           |
                                |                    |              +----------------------+              /-----------/                        +--------------------+                 |                              |
                                |                    |              |If Vagrant            |             /                                                                            |  Install git 2.28+           |
                                |                    |              +----------------------+ <----------/                                                                             +------------------------------+
                                |                    |              |Set message of the day|
                                |                    |              +----------------------+
                                |                    |
                                |                    |              +----------------------+
                                |              (209) |------------> |Install QR libs       |
                                |                    |              |                      |
                                |                    |              |Install python deps   |
                                |                    |              |                      |
                                |                    |              |Install npm           |
                                |                    |              +----------------------|
                                |                    |              |If Vagrant            |
                                |                    |              |   +------------------|
                                |                    |              |.  |Install Haskell   |
                                |                    |              +---+------------------+
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |
                                |                    |            +---------------------------------+
                                |              (635) |----------->|  CONFIGURE_SUBMITTY.py          |
                                |                    |            +---------------------------------+
                                |                    |            |                                 |
                                |                    |            | o Genearates json files         |
                                |                    |            |   o submitty_conf.json          |
                                +--------------------+            |   o email.json                  |
                                                                  |   o submitty_admin.json         |
                                                                  |   o secrets_submity_php.json    |
                                                                  |   o submitty_users.json         |
                                                                  |   o submitty_json               |
                                                                  |   o database.json               |
                                                                  |   o autograding_workers.json    |
                                                                  |   o autograding_containers.json |
                                                                  |                                 |
                                                                  +---------------------------------+
   #+end_src

* README repo

This is an example Puppet infrastructure for the [Puppet Beginner's Guide, Second Edition](http://bitfieldconsulting.com/pbg2). It illustrates all the techniques and concepts described in the book, and draws them together into a complete working infrastructure which you can copy and use in your own projects. While you don't have to buy the book to use the demo repo, I'd obviously be very happy if you did.

To try it out, clone the repo and then run 'vagrant up' from within the repo directory. (If you don't have Vagrant installed, go to the [Vagrant Downloads page](https://www.vagrantup.com/downloads.html)).

Alternatively, to bootstrap a server, all you will need is the IP address or DNS name of the target server. Run the following command from the Puppet repo, replacing `TARGET_SERVER` with the address or name of the server, and `HOSTNAME` with the hostname that you want to set (for example `demo`):

    scripts/puppify TARGET_SERVER HOSTNAME

The demo repo is built on a skeleton Puppet control repo available from [the Puppet GitHub account](https://github.com/puppetlabs/control-repo).

It adds everything required for a typical Puppet infrastructure, including user accounts and SSH keys, SSH and sudoers config, timezone and NTP settings, Hiera data, resources to automatically update and run Puppet, and a bootstrap script for bringing new servers under Puppet management. It also includes a Vagrantfile so you can try out the repo on a Vagrant virtual machine.

You can also find all the code examples from the book in the [Puppet Beginner's Guide example repo](https://github.com/bitfield/puppet-beginners-guide).
